# Generated by Django 4.0.3 on 2022-03-21 12:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9148e1a9-b0b6-47f9-8dde-a38e14d4d8af'), editable=False, primary_key=True, serialize=False),
        ),
    ]
