# Generated by Django 4.0.3 on 2022-03-21 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a67e90fd-43d8-4e1b-a94d-2275541a1992'), editable=False, primary_key=True, serialize=False),
        ),
    ]
