# Generated by Django 4.0.3 on 2022-03-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0008_userlogin_usersignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='newpassword',
        ),
    ]
