# Generated by Django 4.0.3 on 2022-03-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0009_remove_usersignup_newpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSignup',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
