# Generated by Django 4.0.3 on 2022-03-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0010_rename_usersignup_user_delete_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(default='', max_length=255)),
                ('price', models.TextField(default='', max_length=255)),
                ('quantity', models.TextField(default='', max_length=200)),
            ],
        ),
    ]
